name: Build
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install host deps
      run:  sudo apt install -y qemu-user-static binfmt-support
    - uses: actions/checkout@v3
    - name: Build Docker image
      run:  docker build -t buildenv .
    - name: Build
      run:  docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" buildenv ./build.sh
    - name: Upload
      uses: actions/upload-artifact@v7
      with:
        path: out
        name: output
